name: go vet test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  statictest:
    runs-on: ubuntu-latest
    container: golang:1.24
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download statictest binary
        uses: robinraju/release-downloader@v1.8
        with:
          repository: Yandex-Practicum/go-autotests
          latest: true
          fileName: statictest
          out-file-path: .tools
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup autotest binary
        run: |
          chmod -R +x $GITHUB_WORKSPACE/.tools/statictest
          mv $GITHUB_WORKSPACE/.tools/statictest /usr/local/bin/statictest

      - name: Download protoc
        run: |
          # Пример для Linux/macOS
          # wget https://github.com/protocolbuffers/protobuf/releases/download/v<версия>/protoc-<версия>-linux-x86_64.zip
          curl https://github.com/protocolbuffers/protobuf/releases/download/v33.0/protoc-33.0-linux-x86_64.zip
          # unzip protoc-33.0-linux-x86_64.zip -d protoc
      
      - uses: montudor/action-zip@v1
        with:
          args: unzip -qq protoc-33.0-linux-x86_64.zip -d protoc

      - name: Add protoc to PATH
        run: echo "$PWD/protoc/bin" >> $GITHUB_PATH
      # - name: Install Protoc
      #   uses: arduino/setup-protoc@v3 # Or Noelware/setup-protoc@v1
      #   with:
      #     version: 33.x # Specify the desired version 23.x
      #     repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build proto
        run: |
          cd cmd/shortener
          go generate

      - name: Run statictest
        run: |
          go vet -vettool=$(which statictest) ./...
