name: go vet test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  statictest:
    runs-on: ubuntu-latest
    container: golang:1.24
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download statictest binary
        uses: robinraju/release-downloader@v1.8
        with:
          repository: Yandex-Practicum/go-autotests
          latest: true
          fileName: statictest
          out-file-path: .tools
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup autotest binary
        run: |
          chmod -R +x $GITHUB_WORKSPACE/.tools/statictest
          mv $GITHUB_WORKSPACE/.tools/statictest /usr/local/bin/statictest

      - name: Install Protoc
        uses: arduino/setup-protoc@v3 # Or Noelware/setup-protoc@v1
        with:
          version: '33.x' # Specify the desired version 23.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build proto
        run: |
          cd cmd/shortener
          go generate

      - name: Run statictest
        run: |
          go vet -vettool=$(which statictest) ./...
