name: go vet test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  statictest:
    runs-on: ubuntu-latest
    container: golang:1.24
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download statictest binary
        uses: robinraju/release-downloader@v1.8
        with:
          repository: Yandex-Practicum/go-autotests
          latest: true
          fileName: statictest
          out-file-path: .tools
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup autotest binary
        run: |
          chmod -R +x $GITHUB_WORKSPACE/.tools/statictest
          mv $GITHUB_WORKSPACE/.tools/statictest /usr/local/bin/statictest

      - name: Cache protobuf library
        id: cache-protobuf
        uses: actions/cache@v4
        with:
          path: protobuf
          key: ${{ runner.os }}-protobuf
      - name: Build protobuf library
        if: steps.cache-protobuf.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/protocolbuffers/protobuf.git
          cd protobuf
          git submodule update --init --recursive
          ./autogen.sh
          ./autogen.sh
          ./configure
          make
          make check           
      - name: Install protobuf library
        run: |
          cd protobuf
          sudo make install
          sudo ldconfig

      - name: Build proto
        run: |
          cd cmd/shortener
          go generate

      - name: Run statictest
        run: |
          go vet -vettool=$(which statictest) ./...
